### ISSUE TITLE
In Dataset, datasetLink should be plural

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#41]
All the other lists are plural except datasetLink. Should be datasetLinks

**Comment by ypriverol** [comment]
Related to this issue. The current dataset object (@jjcarver and @edeutsch) contains an attribute called `accession` and it is a List of ontology terms. We should rename it to `accessions`  because it is a list.

**Comment by ypriverol** [comment]
Pull Request here https://github.com/HUPO-PSI/proxi-schemas/pull/42

**Comment by edeutsch** [comment]
You're right, I missed accession. Really, I think it should be identifiers. Here's the mapping I need to do:
  our $mapping = { DatasetIdentifier => { name=>"accession", type=>"OntologyTerm" },
                   Species => { name=>"species", type=>"OntologyTermList" },
                   Instrument => { name=>"instruments", type=>"OntologyTerm" },
                   ModificationList => { name=>"modifications", type=>"OntologyTerm" },
                   Contact => { name=>"contacts", type=>"OntologyTermList" },
                   Publication => { name=>"publications", type=>"OntologyTermList" },
                   KeywordList => { name=>"keywords", type=>"OntologyTerm" },
                   FullDatasetLink => { name=>"datasetLink", type=>"OntologyTerm" },
                   DatasetFile => { name=>"dataFiles", type=>"OntologyTerm" },

Instead of "accession" it should be "identifiers" or "datasetIdentifiers"
Maybe instead of "datasetLinks" it should be "fullDatasetLinks"
Maybe instead of dataFiles it should be "datasetFiles"
if we should be consistent with the XML
I vote for consistency.

**Comment by ypriverol** [comment]
@edeutsch I have changed the accession -> identifiers. See that the parameters are now renamed:

 /dataset/{accession} -> /dataset/{identifier}

PR https://github.com/HUPO-PSI/proxi-schemas/pull/42

**Comment by ypriverol** [comment]
All these changes has been included in the latest version of the Swagger definition.
