### ISSUE TITLE
peptide vs peptidoform conflation

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#49]
We are totally conflating the terms peptide and peptidoform. From the /peptides YAML doc:
http://www.peptideatlas.org/api/proxi/v0.1/ui/#/

"The peptide entry point returns global peptidoform statistics across an entire resource. Each peptide contains a summary of the statistics of the peptidoform across the entire resource."

We should aim to be clear and precise. If this endpoint is dealing in peptidoforms (and it does because there are ptms there), then I think we should call it:
/peptidoforms

Do we also want to have /peptides entry point that is scrubbed of all mass mods?
i.e. the /peptides entry point is agnostic to mass mods
the /peptidoforms endpoint requires full handling of mass mods

What do you think?

**Comment by ypriverol** [comment]
Agree 100%. I will change the endpoint.

**Comment by edeutsch** [comment]
great, thanks. while you're making changes, two other things I note:

1) In the spec, peptidoform is sometimes written peptidoForm. It seems unnecessary and undesirable to have a camel hump in the middle of a word

2) Although the psm class has a proteinAccessions, the peptidoform class does not have a proteinAccessions. I assume it should? Or is there a reason not to?

**Comment by edeutsch** [comment]
Okay, I approved and merged the pull request.
BUT, what about my items 1 and 2 immediately above this one?
These were not addressed by the pull request.

**Comment by edeutsch** [comment]
@ypriverol would you consider items 1 and 2 above and create another pull request?

**Comment by edeutsch** [comment]
oops, you are right, I missed it. everything looks good then, thanks.

**Comment by ypriverol** [comment]
Addressed in PR.
