### ISSUE TITLE
Do we need Psm accession?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#55]
Psm is defined in the YAML as:

  Psm:
    required:
      - peptideSequence
    properties: 
      accession:
         type: string 
         description: Accession of the PSM
      usi:
         type: string 
         description: The USI representation for the PSM
...

I like the usi. But what is the accession? Does anyone plan on filling in some other kind of accession for a PSM?

Related, the output does not have datasetIdentifier. All the other components needed to build a USI are part of the output. Except datasetIdentifier. Seems like we should have it. Maybe that's what accession was supposed to be?

**Comment by ypriverol** [comment]
> Psm is defined in the YAML as:
> 
> Psm:
> required:
> - peptideSequence
> properties:
> accession:
> type: string
> description: Accession of the PSM
> usi:
> type: string
> description: The USI representation for the PSM
> ...
> 
> I like the usi. But what is the accession? Does anyone plan on filling in some other kind of accession for a PSM?

Originally this was here to make the difference between to PSMs that share the same USI. In PRIDE we don't have that use case anymore, probably @jjcarver still wants to keep it? If not we can remove it. 

> 
> Related, the output does not have datasetIdentifier. All the other components needed to build a USI are part of the output. Except datasetIdentifier. Seems like we should have it. Maybe that's what accession was supposed to be?

Agree. We should have a dataset accession for easy recovery. What about: 

```json
datasetAccession

   type: string 
   description: Dataset accession 
```

If everyone agree with a +1, I can added it to the schema.

**Comment by edeutsch** [comment]
I rather like identifier better than accession, but accession is okay if that's what everyone else likes.

**Comment by ypriverol** [comment]
Solve in PR https://github.com/HUPO-PSI/proxi-schemas/pull/52
