### ISSUE TITLE
accession input and output

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#56]
/psms input has:

        - name: accession
          in: query 
          type: string 
          description: Dataset accession 

But Psm output has:

      accession:
         type: string 
         description: Accession of the PSM

This is either confusing or an error.

I also suggest that "accession" is too vague. May I suggest datasetIdentifier?
I suppose we use "accession" everywhere else. But I think this is vague and confusing.
At bare minimum, we should not use access for a PSM accession.

How should we resolve?

**Comment by ypriverol** [comment]
Related with issue #55

**Comment by edeutsch** [comment]
my preferred solution is datasetIdentifier input and output and then a psmIdentifier is someone besides me thinks we need it (I don't)

**Comment by ypriverol** [comment]
Solve in PR https://github.com/HUPO-PSI/proxi-schemas/pull/52
