### ISSUE TITLE
is startPosition and endPosition really needed?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#57]
ProteinIdentification: 
    required: 
      - proteinAccession
      - startPosition
      - endPosition 

Is the startPosition and endPosition really required here?
We don't have it trivially available at the moment, so are lying with -1 and -1.
We can get it and will, I guess.
but I'm questioning if we really should have these required. Most proteomics data output doesn't normally capture this?

**Comment by ypriverol** [comment]
I think the idea is to capture the `position` of the peptide identification in protein identification. This is well-documented and traces in formats like `mzIdentML` and `mzTab`. I don't know if the information is available for complete submissions in PRIDE and MassIVE we should remove that information from the API. 

My vote +1 is to make this `optional fields` in that case you don't need to provide -1. Please @jjcarver @edeutsch let me know with a +1 if you like the idea.

**Comment by edeutsch** [comment]
+1, I vote startPosition and endPosition should be optional

**Comment by ypriverol** [comment]
Solve in this PR https://github.com/HUPO-PSI/proxi-schemas/pull/52
