### ISSUE TITLE
default pageNumber?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#58]
in /psms:

        - name: pageNumber
          in: query
          description: Current page to be shown paged psms (default page 1)
          required: false
          type: integer
          default: 0

is the default 0 or 1? schema says 0, but words say one.
This occurs in multiple other places in the schema

Also, we should state clearly whether we are 0-based for page 1 and 1-based for page 1

**Comment by ypriverol** [comment]
Agree, If will refine this in the schema and correct that everywhere.

**Comment by ypriverol** [comment]
I will do it 1-based as other popular apis like github
