### ISSUE TITLE
msrun and filename 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#65]
@edeutsch :

In the parameters of the psm we use the `msrun` and `filename` what is the different between them.

**Comment by edeutsch** [comment]
I had the same question here in my implementation notes, but I neglected to file an issue as you have done. My code currently ignores it. I think it is effectively redundant with msrun. Maybe in theory fileName could specify whether ids should come from a .raw or a .mzML. But msrun can be stretched to the same end if necessary. It is already in USI.

I would vote to remove fileName in both /psms and /spectra if others agree.

**Comment by ypriverol** [comment]
@edeutsch I vote to remove `msrun`. Right now is confusing and duplicated with fileName.

**Comment by edeutsch** [comment]
I would suggest removing fileName instead. A USI is composed of a collection identifier, an msrun name, and a scan number. The msrun parameter is sufficiently abstract that is serves to identify which msrun is meant, independent of the details of fileNames. Which fileNames would be meant anyway? for /spectra is fileName an mzML file or a raw file? For /psms is it an mzML file or an mzIdentML file? or an mzTab file? Seems better to me to abstract that away in the request with just msrun.

**Comment by ypriverol** [comment]
@edeutsch the PR is ready to be merge. Please go for it.

**Comment by edeutsch** [comment]
Does anyone else like @jjcarver want to comment on this before we move ahead?

**Comment by ypriverol** [comment]
@edeutsch this PR has been open for a while. We should merge it and move on. This includes the not implemented error, etc.

**Comment by jjcarver** [comment]
I agree. The PR can be merged as it is.

**Comment by edeutsch** [comment]
oh, I see, I thought you were referring to a pull request removing fileName. But you were referring to the old pull request. I just merged the old PR.

But my intended question to @jjcarver was about removing fileName.
