### ISSUE TITLE
In the PSM object the score should be plural

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#68]
The `searchEngineScore` in psm should be plural because it is a list

searchEngineScore -> searchEngineScores

**Comment by edeutsch** [comment]
I agree it should be plural.

But I'm also wondering if something more general is appropriate. PeptideAtlas does not store actual search engine scores, but rather only probabilities. It seems that in general probabilities or q-values or something like that it more useful than search engine scores anyway (e.g., what does a Mascot score of 35 mean again?) What about renaming this thing to something more like "confidenceScores" or "confidenceMetrics" or something like that? That could hold search engine scores or probabilities or q-values or whatever. What do you think?

**Comment by ypriverol** [comment]
@edeutsch, Im fine with `confidenceScores` because is more generic. Check here the psm endpoint from PRIDE http://wwwdev.ebi.ac.uk/pride/proxi/archive/v0.1/psms?resultType=full&peptideSequence=YNPTWHCIVGR

**Comment by edeutsch** [comment]
Looks fantastic!

**Comment by ypriverol** [comment]
if you agree, we move to `confidentScores`, please give me a 👍

**Comment by edeutsch** [comment]
Should be confidenceScores instead of confidentScores

**Comment by ypriverol** [comment]
@edeutsch can you take a look to this issue https://github.com/HUPO-PSI/proxi-schemas/issues/67

**Comment by ypriverol** [comment]
@edeutsch PR https://github.com/HUPO-PSI/proxi-schemas/pull/69 ready to be approved.
