### ISSUE TITLE
Served datasets can be PX/RPXD or internal accession datasets (MSVnn and PAenn)

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#7]
In PROXI, when referring to served datasets at any resource, for any dataset with a PXD/RPXD, prefer to refer to it with the PXD/RPXD. 

For any datasets without a PXD/RPXD, it is fine to use local identifiers such as MSVnnnn or PAennnnnn

**Comment by edeutsch** [comment]
agreed.
