### ISSUE TITLE
PRIDE USI without interpretation not working?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#74]
This USI with an interpretation works:
http://wwwdev.ebi.ac.uk/pride/proxi/archive/v0.1/spectra?resultType=full&usi=mzspec:PXD000966:CPTAC_CompRef_00_iTRAQ_12_5Feb12_Cougar_11-10-11.mzML:scan:11850:[UNIMOD:214]YYWGGLYSWDMSK[UNIMOD:214]/2

but the same USI without an interpretation does not return a valid response:
http://wwwdev.ebi.ac.uk/pride/proxi/archive/v0.1/spectra?resultType=full&usi=mzspec:PXD000966:CPTAC_CompRef_00_iTRAQ_12_5Feb12_Cougar_11-10-11.mzML:scan:11850

**Comment by ypriverol** [comment]
This issue has been solved.
