### ISSUE TITLE
No attributes for spectra at PRIDE?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/proxi-schemas#75]
This URL returns a spectrum:
http://wwwdev.ebi.ac.uk/pride/proxi/archive/v0.1/spectra?resultType=full&usi=mzspec:PXD000966:CPTAC_CompRef_00_iTRAQ_12_5Feb12_Cougar_11-10-11.mzML:scan:11850:[UNIMOD:214]YYWGGLYSWDMSK[UNIMOD:214]/2

But there are no attributes.

They are not formally required, but seems like some basic metadata might be available?

**Comment by ypriverol** [comment]
Yes we have that metadata. I will put that in my product backlog.

**Comment by ypriverol** [comment]
Done
