### ISSUE TITLE
Way of filtering datasets 

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/proxi-schemas#9]
It would be great if we can filter datasets by the following fields: 

/datasets?pageSize=50&pageNumber=1&resultType=compact
/datasets?pageSize=50&pageNumber=1&resultType=full

- [ ] **Filters (filtering result by columns that are returned)**:
/datasets?species=human
/datasets?species=homo*
/datasets?species=*sapiens
/datasets?species=homo sapiens
/datasets?species=homo sapiens&pageSize=50&pageNumber=1&resultType=compact
/datasets?species=9606
/datasets?species=taxon:9606
/datasets?species=human;mouse	# decide which of these to use or what is conventional
/datasets?species=[human,mouse]
accession=
instrument=
contact=
publication=
modification=
search=liver
search=P12345		# this might be honored by a service, but not mandatory. At some point in the future, we as a consortium might decide to add protein=

Searches: (selecting results based on terms that can apply to any part of the returned records)
/datasets?search=liver
/datasets?species=human&contact=Mann&search=liver

/datasets?species=human&pageSize=50&pageNumber=1&resultType=compact

**Comment by edeutsch** [comment]
agreed. this appears to be reflected in the YAML now, although I have not verified each line.

**Comment by ypriverol** [comment]
Yes they are

**Comment by edeutsch** [comment]
okay, I don't quite understand how this is useful as an issue, however. Wouldn't putting this information in a markdown file at https://github.com/HUPO-PSI/proxi-schemas/tree/master/specs be a bit more useful? That way we can all read it and refine it there as documentation? Or do you propose that this issue remains open until we implement it? I guess I'm wondering what's the event that causes us to close the issue. And once it's closed, then this documentation is hard to find?

**Comment by ypriverol** [comment]
This issue will only be close when this is supported by schema and by specification documents.
